services:
  - type: web
    name: pickgenius-backend
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: USE_PROXY
        value: true
      - key: SCRAPER_API_KEY
        value: ae195cbc8ba44b2bbd6e03daeb64b8150b3e4367688
      - key: GROQ_API_KEY
        value: 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
      # - NBA_API_KEY
      # - FOOTBALL_API_KEY

  - type: web
    name: pickgenius-frontend
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_HOST
        fromService:
          type: web
          name: pickgenius-backend
          property: host
